Model/Config/Indexing.php
Model/Indexing/ProductItemsProvider.php
etc/adminhtml/system.xml

- New configuration yes/no flag in Indexing group
- Logic to add categories hierarchy in products provider if the flag is set

CR-22 Configuration flag and logic for adding all parent categories to products' indexing

---

etc/acl.xml
etc/adminhtml/system.xml

Add ACL for System Configuration

HC-1315: ACL system config

---

Block/Adminhtml/Bulk/Details/BackButton.php
Block/Adminhtml/Bulk/Details/RetryButton.php
Block/Adminhtml/Form/GenericButton.php
Console/Command/RetryBulk.php
Controller/Adminhtml/Bulkoperations/Details.php
Controller/Adminhtml/Bulkoperations/Index.php
Controller/Adminhtml/Bulkoperations/Retry.php
Model/BulkOperation/Options.php
Model/MessageQueue/BulkAccessValidator.php
Model/MessageQueue/BulkPublisher.php
Model/MessageQueue/IndexingOperationValidator.php
Model/MessageQueue/RetryBulkManagement.php
Ui/Component/DataProvider/BulkDataProvider.php
Ui/Component/DataProvider/BulkListing/SearchResult.php
Ui/Component/DataProvider/Operation/SearchResult.php
Ui/Component/Listing/Column/BulkActions.php
etc/acl.xml
etc/adminhtml/di.xml
etc/adminhtml/menu.xml
etc/adminhtml/routes.xml
etc/adminhtml/system.xml
etc/di.xml
view/adminhtml/layout/hawksearch_bulkoperations_details.xml
view/adminhtml/layout/hawksearch_bulkoperations_index.xml
view/adminhtml/ui_component/hawksearch_bulk_details_form.xml
view/adminhtml/ui_component/hawksearch_bulk_listing.xml
view/adminhtml/ui_component/hawksearch_operation_listing.xml

[HC-1315: Update ACL resource name for Systme config](https://github.com/hawksearch/esindexing-magento-2/commit/bc3b73452da0605e5d8b0e01753383ebdc4b39fa)
[HC-1317: Display list of scheduled indexing operation bulks](https://github.com/hawksearch/esindexing-magento-2/commit/160c12c0fbf66909d884f6144f0d288095751696)
[HC-1317: Retry failed operations for a particular bulk](https://github.com/hawksearch/esindexing-magento-2/commit/70274cb69f35dfbd54c3f64e49ea1b86eb5dad08)
[HC-1317: Show details for a particular indexing bulk](https://github.com/hawksearch/esindexing-magento-2/commit/2c81771ef318921cfb610998ababc3698b606d7e)

HC-1317: track current indexing process admin UI

---

Gateway/Validator/GetIndexListBadRequestValidator.php
Model/IndexManagement.php
Model/Indexing/AbstractEntityRebuild.php
Model/Indexing/Entity/Hierarchy/EntityRebuild.php
Model/Indexing/Entity/LandingPage/EntityRebuild.php
Model/Indexing/Entity/Product/EntityRebuild.php
Model/MessageQueue/Consumer.php
etc/di.xml

Fix fatal errors during reindexing when there are no indexes in the Hawksearch Engine

HC-58 empty engine indexing error

---

Model/Indexer/Category.php
Model/Indexer/ContentPage.php
Model/Indexer/Entities.php
Model/Indexer/Product.php
Plugin/Category/CategoryPlugin.php
Plugin/Page/PagePlugin.php
Plugin/Product/AbstractPlugin.php
Plugin/Product/Product/AttributePlugin.php
Plugin/Product/ProductPlugin.php
Plugin/Store/AbstractPlugin.php
Plugin/Store/StoreGroupPlugin.php
Plugin/Store/StoreViewPlugin.php
etc/di.xml

Invalidate indexers on Store view and Store group changes, after Product attribute deletion

HC-1406: Invalidate indexers 

---

Model/BulkOperation/BulkOperationManagement.php
Model/MessageQueue/IndexingOperationValidator.php
Plugin/AsynchronousOperations/BulkStatusPlugin.php
Ui/Component/DataProvider/BulkListing/SearchResult.php
etc/adminhtml/di.xml

feat: exclude Hawksearchh Indexing Bulks from Magento list of Bulk Actions Log
Refs: HC-1409

feat: exclude Hawksearchh Indexing Bulks from Magento list of Bulk Actions Log

---

Model/LandingPage/Attribute/Handler/CustomUrl.php

fix: categories with empty URL break LandingPage update API

---

Logger/LoggerFactory.php

Deprecated LoggerFactory didn't implement deprecated LoggerFactoryInterface
Refs HC-1441

fix: class LoggerFactory implements LoggerFactoryInterface

---

Model/Indexing/Entity/Product/ItemsDataProvider.php

fix: invalid array index because of nonexistent category when indexing

---

CHANGELOG.md
view/frontend/templates/contentwrapper.phtml

fix: cannot read properties of undefined in getID function

---

Model/Product/Attribute/Handler/Composite.php
Model/Product/Attribute/Handler/DefaultHandler.php
Model/Product/Attribute/ValueProcessor.php
Model/Product/Attribute/ValueProcessorInterface.php
etc/di.xml

- Do not roll-up values of SKU attribute of children to parent
- Roll-up attribute values of chldren to parent and meke them unique
Refs: HC-1394, HC-1501, HC-1502

fix: make attribute values of complex products unique

---

Plugin/Checkout/CustomerData/Cart.php
view/frontend/web/js/event-tracking-cart.js

Use cart item price including tax for tracking add2cart event

fix: use price including tax on add2cart event tracking request

---

etc/di.xml

fix: add missing cronjob argument

---

Model/Layout/ConfigProcessor/JsGlobal/RequestConfigProcessor.php
view/frontend/templates/contentwrapper.phtml
view/frontend/web/js/common.js

fix: invalid form key on add to cart form

---

CHANGELOG.md
composer.json

fix: minimal compatible version of connector package is 2.8.0

Hotfix 0.5.1

---

Model/Config/Backend/Serialized/Processor/ProductAttributes.php
Model/Field/Product/AttributeProvider.php
Model/IndexManagement.php

[fix: empty field mapping configuration breaks on saving](https://github.com/hawksearch/esindexing-magento-2/commit/15572252d7ed78fcebbc2c975be075092048d887)
[fix: wrong interface for non-product attributes on filed mapping saving](https://github.com/hawksearch/esindexing-magento-2/commit/e9587604bdd049b7df43159ccbd2cf904e7285ed)
[chore: rearange debug messages on switching indices](https://github.com/hawksearch/esindexing-magento-2/commit/a177a5eafa4c3440b667ca0d6f00da9f4f7483d1)

fix: field-attribute mapping issues

---

Model/Config/Indexing/FailureRecovery.php
Model/Cron/RetryFailedOperations.php
etc/adminhtml/system.xml
etc/config.xml
etc/cron_groups.xml
etc/crontab.xml
etc/di.xml

feat: disable hawksearch_retry_failed_operations cron by config

---

Console/Command/RetryBulk.php

fix: forbid retrying completed operations

---

CHANGELOG.md
Model/Indexing/Entity/Product/ItemsDataProvider.php
composer.json

fix: sql error on indexing product with no categories

---

CHANGELOG.md
Model/Indexing/AbstractEntityRebuild.php
Model/Indexing/Entity/Product/ItemsDataProvider.php
Model/Indexing/EntityTypePool.php
Model/Indexing/EntityTypePoolInterface.php
Model/Product/Attribute/ExcludeNotVisibleProductsFlag/DefaultProvider.php
Model/Product/Attribute/ExcludeNotVisibleProductsFlag/IncludeProvider.php
Model/Product/Attribute/ExcludeNotVisibleProductsFlagInterface.php
Model/Product/Attribute/Handler/Composite.php
Model/Product/Attribute/ValueProcessor.php
composer.json
etc/di.xml

[fix: child attribute values doesn't roll-up to parent product](https://github.com/hawksearch/esindexing-magento-2/commit/62170fc2b1293182bf0a4fc6dd4575b33c2a1da5)
Ref: HC-1630

Hotfix 0.6.4

---

Model/Product/Attributes.php

fix: send sku field to index by default

---

.gitignore
.husky/commit-msg
.husky/prepare-commit-msg.disabled
composer.json
package-lock.json
package.json
phpstan.neon

[ci: add static code analysers](https://github.com/hawksearch/esindexing-magento-2/commit/49b831e0c267ff23b4b672e0dbdc12d953db6ca6)
[ci: follow conventional commits with husky and commitizen](https://github.com/hawksearch/esindexing-magento-2/commit/277d945dbbd8291d3682760e9d831a404b349adb)

ci: static code analysers and commit lint

---

Api/Data/ClientDataInterface.php
Api/Data/CoordinateInterface.php
Api/Data/FacetBoostBuryInterface.php
Api/Data/FacetInterface.php
Api/Data/FacetRangeModelInterface.php
Api/Data/FacetValueOrderInfoInterface.php
Api/Data/FieldInterface.php
Api/Data/HierarchyInterface.php
Api/Data/IndexItemsContextInterface.php
Api/Data/SearchRequestInterface.php
Model/ClientData.php
Model/Config/ApiSettings.php
Model/Indexing/Entity/Hierarchy/ItemsDataProvider.php
Model/Indexing/Entity/LandingPage/ItemsDataProvider.php
Model/Product/Attribute/ExcludeNotVisibleProductsFlag/DefaultProvider.php
Model/Product/Attribute/ExcludeNotVisibleProductsFlag/IncludeProvider.php
Model/Product/Attribute/ExcludeNotVisibleProductsFlagInterface.php
Observer/SendCookieOnCartCompleteObserver.php
Plugin/Checkout/CustomerData/Cart.php
Plugin/ConsumerProcessorPlugin.php
Plugin/Eav/Entity/Attribute/Source/Table/SpecificOptionsPlugin.php
Plugin/Store/StoreViewDisableIndexingPlugin.php
Plugin/Store/StoreViewPlugin.php
etc/acl.xml
etc/indexer.xml
etc/mview.xml
view/adminhtml/ui_component/hawksearch_bulk_details_form.xml
view/adminhtml/ui_component/hawksearch_bulk_listing.xml
view/adminhtml/ui_component/hawksearch_operation_listing.xml
view/frontend/web/js/event-tracking.js

| Branch?       | develop
| Issues        | Fix HC-1702 
A follow up to update types hints in method arguments.

feat: add type hints to method arguments

---

.github/PULL_REQUEST_TEMPLATE.md

| Bug fix?      | no 
| Issues        |

docs: add github pull request template

---

Model/Indexing/Entity/Product/EntityRebuild.php
Model/Product/Field/Handler/DefaultHandler.php
Model/Product/Field/Handler/ImageUrl.php

| Issues        | 
Not a breaking change

fix: change private method param type to strict type

---

Plugin/Indexing/Entity/Product/EntityRebuildPlugin.php

feat(plugin): remove argument default value in constructor

---

Plugin/Store/AbstractPlugin.php
Plugin/Store/StoreGroupPlugin.php
Plugin/Store/StoreViewPlugin.php

| Bug fix?      | no 
| Issues        | 
Plugins do not follow BC rules so this is not a breaking change

feat(plugin): add types to protected properties

---

.github/PULL_REQUEST_TEMPLATE.md

| Branch?       | 0.8 
| Issues        |

docs: update github pull request template

---

Block/Adminhtml/System/Config/Product/CustomAttributes.php
Test/Unit/Block/Adminhtml/System/Config/Product/CustomAttributesTest.php
phpstan.neon
view/adminhtml/templates/system/config/product/custom-attributes-js.phtml

| Deprecations? | yes
This is also a step forward for closing the API by turning protected methods to private if class is not designed to be extended.  This allows design flaws to be found more easily and gives you the opportunity to evolve your code by creating well defined extension points.
We've just started following the concept to cover all new features and updates with unit tests. So that we a re moving to out goal to cover as much as possible classes with unit tests.

feat(CustomAttributes): deprecate protected methods

---

Model/Indexing/Entity/LandingPage/EntityRebuild.php
Model/Indexing/EntityType/EntityTypeAbstract.php

Fixing some previous deprecations

fix: deprecations of properties and parameters

---

Model/Layout/ConfigProcessor/JsGlobal/CatalogConfigProcessor.php
Model/Layout/ConfigProcessor/Vue/VueAdditionalParametersProcessor.php
Registry/CurrentCategory.php
Ui/Component/DataProvider/BulkListing/SearchResult.php

| Tickets       |
Refactor conditionals based on phpstan inspections

refactor: minor conditional errors (phpstan)

---

phpstan.neon

| Tests pass?   | no
Static code analiser config update: exclude analyzing Test fixture files

ci: ignore errors in phpstan config

---

Api/Data/ClientDataInterface.php
Api/Data/FacetBoostBuryInterface.php
Api/Data/FacetInterface.php
Api/Data/IndexItemsContextInterface.php
Api/Data/SearchRequestInterface.php
Plugin/Category/CategoryPlugin.php

| Bug fix?      | yes 
| New feature?  | no 
| BC breaks?    | no 
| Tests pass?   | no
Addition fix to #115

fix: use FQN in @return for Api\Data interfaces

---

Helper/ObjectHelper.php
Model/ClientData.php
Model/Facet.php
Model/FacetBoostBury.php
Model/IndexItemsContext.php
Model/SearchRequest.php
Test/Unit/Model/ClientDataTest.php
Test/Unit/Model/FacetBoostBuryTest.php
Test/Unit/Model/FacetTest.php
Test/Unit/Model/IndexItemsContextTest.php
Test/Unit/Model/SearchRequestTest.php
phpstan.neon

| Branch?       | 0.8 
| Tickets       |

fix: default object values when initialising DTO classes

---

Model/Product/Attributes.php

perf: add caching for config fields mapping, unserialize once

---

Model/Product/Field/Handler/DefaultHandler.php

perf: add caching for attribute source

---

Model/Api/SearchCriteria/JoinProcessor/ProductPrices.php
Model/Config/Products.php
Model/Product/EntityPriceObserver.php
Model/Product/ProductType/DefaultType.php
Test/Unit/Model/Config/ProductsTest.php
etc/adminhtml/system.xml
etc/config.xml

Adding feature to Enable/Disable price indexing by configuration values 
`hawksearch_product_settings/products/index_prices`
`hawksearch_product_settings/products/index_customer_group_prices`

feat: enable price indexing by config
